app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='main'),
    path('weather/', include('main.urls'), name='weather'),
    path('user/', include('user.urls'), name='user'),
    path('cities/', include('cities.urls'), name='cities'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cities/urls.py
from django.urls import path, include
from . import views

app_name = 'cities'

urlpatterns = [
    path('', views.CityListView.as_view(), name='list'),
    path('search/', views.CityListView.as_view(), name='search'),
    path('<slug:slug>/', views.CityDetailView.as_view(), name='detail'),
    path('rate-city/<slug:slug>/', views.RateCityView.as_view(), name='rate_city'),
    path('<slug:slug>/<slug:attr_slug>/', views.AttractionDetailView.as_view(), name='attr_detail'),
    path('add_review-attr/<slug:city_slug>/<slug:attr_slug>/', views.AddReviewAttrView.as_view(), name='add_review_attr'),
	path('remove_review-attr/<slug:city_slug>/<slug:attr_slug>/<int:pk>/', views.RemoveReviewAttrView.as_view(), name='remove_review_attr')
]

user/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='user/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
            template_name='user/password_reset_form.html',
            email_template_name='user/password_reset_email.html',
            success_url=reverse_lazy('user:password_reset_done'),
    ),
    name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html', success_url=reverse_lazy('user:password_reset_complete')
    ),
    name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
]

cities/models.py
from django.db import models
from django.db.models import Avg

from user.models import User


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)

    class Meta:
        db_table = 'category'
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        ordering = ('id',)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    country = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=True, null=True, verbose_name='Description')
    region = models.CharField(max_length=100, blank=False)
    image = models.ImageField(upload_to='cities', blank=True, null=True)
    population = models.BigIntegerField(blank=False, null=True)
    average_rating = models.FloatField(default=0)

    class Meta:
        db_table = 'city'
        verbose_name = 'city'
        verbose_name_plural = 'cities'
        ordering = ('id',)


    def update_average_rating(self):
        ratings = self.ratings.all()
        if ratings.exists():
           self.average_rating = ratings.aggregate(models.Avg('rating'))['rating__avg']
        else:
           self.average_rating = 0
        self.save()

    def get_average_rating(self):
         return self.ratings.aggregate(Avg('rating'))['rating__avg'] or 0

    def get_total_count(self):
        return self.ratings.count()

    def __str__(self):
        return f'Name: {self.name}, Country: {self.country}'


class Attraction(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True, verbose_name='Description')
    image = models.ImageField(upload_to='attrs', blank=True, null=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    categories = models.ManyToManyField(Category, related_name='attractions')

    class Meta:
        db_table = 'attraction'
        verbose_name = 'attraction'
        verbose_name_plural = 'attractions'
        ordering = ('id',)

    def __str__(self):
        return f'Name: {self.name}, City: {self.city}, Categories: {self.categories}'


class Rating(models.Model):
    city = models.ForeignKey(City, related_name='ratings', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField()

    class Meta:
        unique_together = ('city', 'user')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.city.update_average_rating()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.city.update_average_rating()



class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    attraction = models.ForeignKey(Attraction, on_delete=models.CASCADE)
    text = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}: {self.attraction}'

cities/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text',]
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'text': 'Review',
        }

cities/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, View, DetailView, FormView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ReviewForm
from .models import City, Attraction, Rating, Review, Category
from .utils import query_search


class CityListView(ListView):
    model = City
    template_name = 'cities/city_list.html'
    context_object_name = 'cities'

    def get_queryset(self):
        query = self.request.GET.get("q")
        order_by = self.request.GET.get("order_by")

        if query:
            cities = query_search(query)
        else:
            cities = City.objects.all()

        if order_by and order_by != 'default':
            cities = cities.order_by(order_by)

        return cities

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'City list'
        return context


class CityDetailView(LoginRequiredMixin, DetailView):
    model = City
    template_name = 'cities/city_detail.html'
    context_object_name = 'city'

    def get_object(self, queryset=None):
        slug = self.kwargs['slug']
        return get_object_or_404(City, slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        city = self.get_object()
        selected_categories = self.request.GET.getlist('category')

        if selected_categories:
            context['attractions'] = Attraction.objects.filter(
                city=city,
                categories__slug__in=selected_categories
            ).distinct()
        else:
            context['attractions'] = Attraction.objects.filter(city=city)

        context['categories'] = Category.objects.all()
        context['title'] = 'City detail'
        context['average_rating'] = city.get_average_rating()
        context['total_reviews'] = city.get_total_count()
        return context


class AttractionDetailView(DetailView):
    model = Attraction
    template_name = 'cities/attraction_detail.html'
    context_object_name = 'attraction'

    def get_object(self, queryset=None):
        attr_slug = self.kwargs['attr_slug']
        return get_object_or_404(Attraction, slug=attr_slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        attraction = self.get_object()
        context['title'] = 'Attraction detail'
        context['attraction'] = attraction
        context['city.slug'] = attraction.city.slug
        context['city'] = attraction.city
        context['reviews'] = Review.objects.filter(attraction=attraction)
        return context


class RateCityView(View):
    def post(self, request, slug):
        city = get_object_or_404(City, slug=slug)
        rating_value = request.POST.get('rating')

        if rating_value:
            try:
                rating_value = int(rating_value)
                if 1 <= rating_value <= 5:
                    Rating.objects.update_or_create(
                        city=city,
                        user=request.user,
                        defaults={'rating': rating_value}
                    )
                else:
                    pass
            except ValueError:
                pass

        return redirect('cities:detail', slug=city.slug)


class AddReviewAttrView(FormView):
    template_name = 'cities/attraction_detail.html'
    form_class = ReviewForm
    model = Review
    success_url = 'cities:attraction_detail'
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.attraction = get_object_or_404(Attraction, slug=self.kwargs['attr_slug'])
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('cities:attr_detail', kwargs={
            'slug': self.kwargs['city_slug'],
            'attr_slug': self.kwargs['attr_slug']
        })

class RemoveReviewAttrView(LoginRequiredMixin, DeleteView):
    model = Review
    template = 'cities/attraction_detail.html'
    
    def get_success_url(self) -> str:
        return reverse_lazy('cities:attr_detail', kwargs={
            'slug': self.kwargs['city_slug'],
            'attr_slug': self.kwargs['attr_slug'],
        })
    
    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)
    
    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)
    
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)
		
    
    
	
	
    

cities/templates/cities/attraction_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'deps/css/attr_detail.css' %}">

	<div class="attraction-card">
        <img src="{{ attraction.image.url }}" alt="{{ attraction.name }}">
        <h4>{{ attraction.name }}</h4>
        <p>{{ attraction.description }}</p>
    </div>
	
	{% if user.is_authenticated %}
		<form id="review-form" method="post" action="{% url 'cities:add_review_attr' city.slug attraction.slug %}">
			{% csrf_token %}
			<div class="form-group">
				<label for="review-text">Your Review</label>
				<textarea id="review-text" name="text" class="form-control" rows="4" required></textarea>
			</div>
			<button type="submit" class="btn btn-primary">Submit</button>
		</form>
	{% else %}
		<p>Please <a href='{% url "user:login" %}'>login</a> to add review</p>
	{% endif %}

    {% for review in reviews %}
        <div class="review">
            <p><strong>{{ review.user.username }}</strong> wrote:</p>
            <p>{{ review.text }}</p>
            <small>Date: {{ review.created_at|date:"d.m.Y H:i" }}</small>
			{% if review.user == request.user %}
				<button class='btn'><a href="{% url 'cities:remove_review_attr' city.slug attraction.slug review.id %}">Delete</a></button>
			{% endif %}
        </div>
    {% endfor %}

{% endblock %}

cities/templates/cities/city_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}

<link rel="stylesheet" href="{% static 'deps/css/city_detail.css' %}">

<div class="city-header">
    <img src="{{ city.image.url }}" alt="{{ city.image }}">
    <h1>{{ city.name }}</h1>
    <p><strong>Country:</strong> {{ city.country }}</p>
    <p><strong>Population:</strong> {{ city.population|intcomma }}</p>
    <p>{{ city.description }}</p>
</div>

<div class="rating-container">
    <form id="rating-form" method="post" action="{% url 'cities:rate_city' city.slug %}">
        {% csrf_token %}
        <input type="hidden" id="rating-input" name="rating" value="0">
        <div class="star-rating">
            <span class="star" data-rating="1">&#9733;</span>
            <span class="star" data-rating="2">&#9733;</span>
            <span class="star" data-rating="3">&#9733;</span>
            <span class="star" data-rating="4">&#9733;</span>
            <span class="star" data-rating="5">&#9733;</span>
        </div>
    </form>
    <p>Average rating: {{ average_rating }}</p>
    <p>Total reviews: {{ total_reviews }}</p>
</div>


<div class="dropdown mb-4">
    <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Filters
    </button>
    <form action="{% url 'cities:detail' city.slug %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
        <p class="text-white mx-3 mt-3">Sort by categories:</p>

        {% for category in categories %}
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="category" id="{{ category.slug }}" value="{{ category.slug }}"
                        {% if category.slug in selected_categories %}checked{% endif %}>
                <label class="form-check-label" for="{{ category.slug }}">
                    {{ category.name }}
                </label>
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary mx-3 mt-3">Apply</button>
    </form>
</div>

<div class="attractions">
    {% for attraction in attractions %}
    <div class="attraction-card">
        <a href="{% url 'cities:attr_detail' city.slug attraction.slug %}">
            <img src="{{ attraction.image.url }}" alt="{{ attraction.name }}">
            <h4>{{ attraction.name }}</h4>
        </a>
        <p>{{ attraction.description|truncatechars:222 }}</p>
        {% for category in attraction.categories.all %}
            {{ category.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock %}

cities/templates/cities/city_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load string_multiplicator %}

{% block content %}

<link rel="stylesheet" href="{% static 'deps/css/city.css' %}">

<form class="d-flex mb-4" role="search" action="{% url "cities:search" %}" method="get">
    <input class="form-control me-2" type="search" name="q" placeholder="Enter the name of the city" aria-label="Search">
    <button class="btn btn-outline-success text-black" type="submit">Search</button>
</form>

<div class="dropdown mb-4">
    <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        Filters
    </button>
    <form action="{% url 'cities:search' %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
        {% if request.GET.q %}
            <input type="hidden" name="q" value="{{ request.GET.q }}">
        {% endif %}
        <p class="text-white mx-3 mt-3">Sort by rating:</p>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="rating_high" value="-average_rating"
            {% if request.GET.order_by == '-rating' %}checked{% endif %}>
            <label class="form-check-label" for="rating_high">
                From highest to lowest
            </label>
        </div>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="rating_low" value="average_rating"
            {% if request.GET.order_by == 'rating' %}checked{% endif %}>
            <label class="form-check-label" for="rating_low">
                From lowest to highest
            </label>
        </div>

        <p class="text-white mx-3 mt-3">Sort by population:</p>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="population_high" value="-population"
            {% if request.GET.order_by == '-rating' %}checked{% endif %}>
            <label class="form-check-label" for="rating_high">
                From highest to lowest
            </label>
        </div>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="population_low" value="population"
            {% if request.GET.order_by == 'rating' %}checked{% endif %}>
            <label class="form-check-label" for="rating_low">
                From lowest to highest
            </label>
        </div>

        <p class="text-white mx-3 mt-3">Sort by alphabet:</p>
        <div class="form-check text-white mx-3">
            <input class="form-check-input" type="radio" name="order_by" id="name_az" value="name"
            {% if request.GET.order_by == 'name' %}checked{% endif %}>
            <label class="form-check-label" for="name_az">
                From A to Z
            </label>
        </div>

        <button type="submit" class="btn btn-primary mx-3 mt-3">Apply</button>
    </form>
</div>

{% if request.GET.q %}
    <h3 class="mt-4">Results by using query {{ request.GET.q }}</h3>
{% endif %}

{% if not cities %}
    <h2 class="mt-4">We can't find anything using your query</h2>
{% endif %}

<div class="container">
    <div class="city-list">
        {% for city in cities %}
            <div class="city-card">
                <a href="{% url 'cities:detail' city.slug %}">
                    <img src="{{ city.image.url }}" alt="{{ city.image }}" class="city-image">
                </a>
                <div class="city-info">
                    <a href="{% url 'cities:detail' city.slug %}">
                        <h3>{{ city.name }}</h3>
                    </a>
                    <p><strong>Country:</strong> {{ city.country }}</p>
                    <p><strong>Population:</strong> {{ city.population|intcomma }}</p>

                    <p><strong>Average Rating:</strong> {% filter multiply:city.average_rating %}⭐{% endfilter %}</p>

                    <p>{{ city.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}