app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='main'),
    path('weather/', include('main.urls'), name='weather'),
    path('user/', include('user.urls'), name='user'),
    path('cities/', include('cities.urls'), name='cities'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cities/urls.py
from django.urls import path, include
from . import views

app_name = 'cities'

urlpatterns = [
    path('', views.CityListView.as_view(), name='list'),
    path('search/', views.CityListView.as_view(), name='search'),
    path('<slug:slug>/', views.CityDetailView.as_view(), name='detail'),
    path('rate-city/<slug:slug>/', views.RateCityView.as_view(), name='rate_city'),
    path('<slug:slug>/<slug:attr_slug>/', views.AttractionDetailView.as_view(), name='attr_detail'),
    path('add_review-attr/<slug:city_slug>/<slug:attr_slug>/', views.AddReviewAttrView.as_view(), name='add_review_attr'),
	path('remove_review-attr/<slug:city_slug>/<slug:attr_slug>/<int:pk>/', views.RemoveReviewAttrView.as_view(), name='remove_review_attr')
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.WeatherView.as_view(), name='weather'),
    path('search/', views.WeatherView.as_view(), name='search'),
]

user/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='user/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
            template_name='user/password_reset_form.html',
            email_template_name='user/password_reset_email.html',
            success_url=reverse_lazy('user:password_reset_done'),
    ),
    name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password_reset_confirm.html', success_url=reverse_lazy('user:password_reset_complete')
    ),
    name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'), name='password_reset_complete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'deps/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static "deps/pictures/favicon-32x32.png" %}">
</head>
<body>
<div class="content-wrapper">
    {% if messages %}
        <div id="popup-messages">
            {% for message in messages %}
                <div class="message-popup {% if message.tags %}{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <header>
        <div class="container">
            <h1 class="logo-font">Adventure Time</h1>
            <nav>
                <ul>
                
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'main' %}">Home</a></li>
                        <li><a href="{% url 'weather:weather' %}">Weather</a></li>
                        <li><a href="{% url 'cities:list' %}">Cities</a></li>
                        <li><a href="{% url 'user:profile' %}">Profile</a></li>
                        <li>{{ user.username }} | <a href='{% url 'user:logout' %}'>Logout</a></li>
                        
                        {% if user.is_staff %}
                            <li><a href="{% url 'admin:index' %}">Admin</a></li>
                        {% endif %}    
                    {% else %}
                        <li><a href="{% url 'user:login' %}">Home</a></li>
                        <li><a href="{% url 'user:login' %}">Profile</a></li> 
                        <li><a href='{% url 'user:login' %}'>Login</a> | <a href='{% url 'user:register' %}'>Registration</a></li>
                    {% endif %}
                
                </ul>
            </nav>
        </div>
    </header>

    <main>
        {% block content %}
            
        {% endblock %}
    </main>
</div>

<footer>
    <p>&copy; 2024 Weather Site. All rights reserved.</p>
</footer>

<script src="{% static 'deps/js/js.js' %}"></script>
<script src="{% static 'deps/js/star_rating.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>