app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='main'),
    path('weather/', include('main.urls'), name='weather'),
    path('user/', include('user.urls'), name='user'),
    path('cities/', include('cities.urls'), name='cities'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

app_name = 'weather'

urlpatterns = [
    path('', views.WeatherView.as_view(), name='weather'),
    path('search/', views.WeatherView.as_view(), name='search'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from .utils import weather_api as w
from main.utils.api_client import APIClient as api
from datetime import datetime, timedelta


class WeatherView(LoginRequiredMixin, TemplateView):
    template_name = 'main/weather.html'

    def get_context_data(self, **kwargs):
        search_city = self.request.GET.get('city', None)
        date = self.request.GET.get('date', 'today')
        profile_city = self.request.user.city
        current_time = datetime.now()

        if not search_city and not profile_city:
            context = super().get_context_data(**kwargs)
            context['error'] = 'Please enter the name of the city first'
            context['weather'] = {'date': date}
            return context

        city = search_city if search_city else profile_city

        if date == 'today':
            first_data, second_data, third_data, fourth_data, fifth_data = api.get_today_data(city, current_time)
        elif date == 'tomorrow':
            first_data, second_data, third_data, fourth_data, fifth_data = api.get_tomorrow_data(city, current_time)
        elif date == '5_days':
            first_data, second_data, third_data, fourth_data, fifth_data = api.get_5_days_data(city, current_time)
        elif date == '3_days':
            first_data, second_data, third_data, fourth_data, fifth_data = api.get_3_days_data(city, current_time)
        else:
            first_data = None
            second_data = None
            third_data = None

        if first_data == 'City not found' or first_data is None:
            context = super().get_context_data(**kwargs)
            context['error'] = 'There is no data for that city'
            return context

        first = w.Weather_API(**first_data)
        second = w.Weather_API(**second_data)
        third = w.Weather_API(**third_data)

        if date == '5_days':
            fourth = w.Weather_API(**fourth_data)
            fifth = w.Weather_API(**fifth_data)


        context = super().get_context_data(**kwargs)
        context['title'] = 'Weather'
        context['weather'] = {
            'first': first,
            'second': second,
            'third': third,
            'fourth': fourth if date == '5_days' else None,
            'fifth': fifth if date == '5_days' else None,
            'date': date
        }
        return context


class HomePage(TemplateView):
    template_name = 'base.html'
    extra_context = {'title': 'Home Page'}

main/templates/main/weather.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <link rel="stylesheet" href="{% static 'deps/css/weather.css' %}">

    <title>Погода</title>

    <div class="search-container">
        <div class="search-form">
            <form id="weather-form" role="search" method="get" action="{% url 'weather:search' %}">
                <input type="search" class="search-input" aria-label="Search" name="city" placeholder="Enter city name..." value="{{ request.GET.city }}">
                <input type="hidden" id="date-input" name="date" value="{{ weather.date }}">
                <button class="search-button" type="submit">Search</button>
            </form>
        </div>
    <div class="date-buttons">
        <button class="date-button {% if weather.date == 'today' %}active-date-button{% endif %}"
                onclick="document.getElementById('date-input').value = 'today'; document.getElementById('weather-form').submit();">
            Today
        </button>
        <button class="date-button {% if weather.date == 'tomorrow' %}active-date-button{% endif %}"
                onclick="document.getElementById('date-input').value = 'tomorrow'; document.getElementById('weather-form').submit();">
            Tomorrow
        </button>
        <button class="date-button {% if weather.date == '3_days' %}active-date-button{% endif %}"
                onclick="document.getElementById('date-input').value = '3_days'; document.getElementById('weather-form').submit();">
            3 Days
        </button>
        <button class="date-button {% if weather.date == '5_days' %}active-date-button{% endif %}"
                onclick="document.getElementById('date-input').value = '5_days'; document.getElementById('weather-form').submit();">
            5 Days
        </button>
    </div>
</div>

    {% if error %}
        <div class="error-message">
            {{ error }}
        </div>
    {% else %}
        <div class="weather-container">

            <div class="weather-box">
                <div class="temperature">{{ weather.first.header }}</div>
                {% if weather.first.weather == 'Rain' %}
                    <img src="{% static "deps/pictures/rain.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.first.weather == 'Clouds' %}
                    <img src="{% static "deps/pictures/cloud.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.first.weather == 'Clear' %}
                    <img src="{% static "deps/pictures/sunny.png" %}" alt="Weather" class="weather-icon">
                {% endif %}
                <div class="temperature">{{ weather.first.temp }}°C</div>
                <div class="status">{{ weather.first.weather }}</div>
                <div class="wind-speed">Wind: {{ weather.first.wind_speed }} m/s</div>
                <div class="humidity">Humidity: {{ weather.first.humidity }}%</div>
            </div>

            <div class="weather-box">
                <div class="temperature">{{ weather.second.header }}</div>
                {% if weather.second.weather == 'Rain' %}
                    <img src="{% static "deps/pictures/rain.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.second.weather == 'Clouds' %}
                    <img src="{% static "deps/pictures/cloud.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.second.weather == 'Clear' %}
                    <img src="{% static "deps/pictures/sunny.png" %}" alt="Weather" class="weather-icon">
                {% endif %}
                <div class="temperature">{{ weather.second.temp }}°C</div>
                <div class="status">{{ weather.second.weather }}</div>
                <div class="wind-speed">Wind: {{ weather.second.wind_speed }} m/s</div>
                <div class="humidity">Humidity: {{ weather.second.humidity }}%</div>
            </div>

            <div class="weather-box">
                <div class="temperature">{{ weather.third.header }}</div>
                {% if weather.third.weather == 'Rain' %}
                    <img src="{% static "deps/pictures/rain.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.third.weather == 'Clouds' %}
                    <img src="{% static "deps/pictures/cloud.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.third.weather == 'Clear' %}
                    <img src="{% static "deps/pictures/sunny.png" %}" alt="Weather" class="weather-icon">
                {% endif %}
                <div class="temperature">{{ weather.third.temp }}°C</div>
                <div class="status">{{ weather.third.weather }}</div>
                <div class="wind-speed">Wind: {{ weather.third.wind_speed }} m/s</div>
                <div class="humidity">Humidity: {{ weather.third.humidity }}%</div>
            </div>

        {% if weather.date == '5_days' %}
        	<div class="weather-box">
                <div class="temperature">{{ weather.fourth.header }}</div>
                {% if weather.fourth.weather == 'Rain' %}
                    <img src="{% static "deps/pictures/rain.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.fourth.weather == 'Clouds' %}
                    <img src="{% static "deps/pictures/cloud.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.fourth.weather == 'Clear' %}
                    <img src="{% static "deps/pictures/sunny.png" %}" alt="Weather" class="weather-icon">
                {% endif %}
                <div class="temperature">{{ weather.fourth.temp }}°C</div>
                <div class="status">{{ weather.fourth.weather }}</div>
                <div class="wind-speed">Wind: {{ weather.fourth.wind_speed }} m/s</div>
                <div class="humidity">Humidity: {{ weather.fourth.humidity }}%</div>
            </div>

            <div class="weather-box">
                <div class="temperature">{{ weather.fifth.header }}</div>
                {% if weather.fifth.weather == 'Rain' %}
                    <img src="{% static "deps/pictures/rain.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.fifth.weather == 'Clouds' %}
                    <img src="{% static "deps/pictures/cloud.png" %}" alt="Weather" class="weather-icon">
                {% elif weather.fifth.weather == 'Clear' %}
                    <img src="{% static "deps/pictures/sunny.png" %}" alt="Weather" class="weather-icon">
                {% endif %}
                <div class="temperature">{{ weather.fifth.temp }}°C</div>
                <div class="status">{{ weather.fifth.weather }}</div>
                <div class="wind-speed">Wind: {{ weather.fifth.wind_speed }} m/s</div>
                <div class="humidity">Humidity: {{ weather.fifth.humidity }}%</div>
            </div>
        {% endif %}
        </div>
    {% endif %}

{% endblock %}